import "./import/modules";
import "./import/components";
import "./import/tab";
import "./import/burger"
import "./import/list"
import "./import/input"
import "./import/slider"
import "./import/showMore"
import "./import/swiper"
import "./import/showSettings"
import "./import/showImage"
import './import/fullComplect'
import './import/dynamicAdapt'
import './import/showFeedback'
import './import/calculator'